### ISSUE TITLE
Cmtio as notion widget

### ISSUE THREAD

**Issue by VidhyaVarshanyJS** [napthedev/cmtio#2]
is there any possibility to use cmtio in notion as a widget ?

**Comment by phongna07** [comment]
I don't have any experience with notion widgets, but if you can add an iframe into notion, maybe it will be ok?

**Comment by VidhyaVarshanyJS** [comment]
> I don't have any experience with notion widgets, but if you can add an iframe into notion, maybe it will be ok?

Yeah, Thanks. You have done a wonderful dev art .
